//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOKACIJA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOKACIJA()
        {
            this.PUTOVANJE = new HashSet<PUTOVANJE>();
        }
    
        public int sifra_grada { get; set; }
        public string sifra_drzave { get; set; }
        public string ime_grada { get; set; }
    
        public virtual DRZAVA DRZAVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUTOVANJE> PUTOVANJE { get; set; }
    }
}
