//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPPP09Entities : DbContext
    {
        public RPPP09Entities()
            : base("name=RPPP09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DRZAVA> DRZAVA { get; set; }
        public virtual DbSet<LOKACIJA> LOKACIJA { get; set; }
        public virtual DbSet<PUTOVANJE> PUTOVANJE { get; set; }
    }
}
